import type { Metadata } from "next";
import "./globals.css";
  import Context from "./context";
export const metadata: Metadata = {
  title: "AgentKit Quickstart",
  description: "Generated by `create-onchain-agent`, a Next.js template for AgentKit",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
          <body>
          <Context>

            <main className="flex-grow flex items-center justify-center px-2 bg-gray-900">
            {children}
          </main>
          </Context>
        </body>
      </html>
  );
}
